# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'rtDatabase' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  # Pods for rtDatabase
  target 'rtDatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rtDatabase-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for rtDatabase-tvOS

  target 'rtDatabase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
